export const works = [
  {
    id: '01',
    name: 'Name1',
    description:
      'An individual effort creating a social travel app consuming TFLs public API and allows users to plan journeys as well as check for live travel updates. The app will include a social feature where users can post pictures and statuses mimicking a social media platform.',
    tech: [
      'React.js',
      'JavaScript (ES6)',
      'HTML5/SASS',
      'Axios',
      'JSON',
      'React.js',
      'JavaScript (ES6)',
      'HTML5/SASS',
      'Axios',
      'JSON',
      'JSON',
    ],
    linkRepo: '#',
    linkDemo: '#',
    imgLink: 'https://via.placeholder.com/1920x1080',
  },
  {
    id: '02',
    name: 'Name2',
    description:
      'An individual effort creating a social travel app consuming TFLs public API and allows users to plan journeys as well as check for live travel updates. The app will include a social feature where users can post pictures and statuses mimicking a social media platform.',
    tech: [
      'React.js',
      'JavaScript (ES6)',
      'HTML5/SASS',
      'Axios',
      'JSON',
      'React.js',
      'JavaScript (ES6)',
      'HTML5/SASS',
      'Axios',
      'JSON',
    ],
    linkRepo: '#',
    linkDemo: '#',
    imgLink: 'https://via.placeholder.com/1920x1080',
  },
  {
    id: '03',
    name: 'Name3',
    description:
      'An individual effort creating a social travel app consuming TFLs public API and allows users to plan journeys as well as check for live travel updates. The app will include a social feature where users can post pictures and statuses mimicking a social media platform.',
    tech: [
      'React.js',
      'JavaScript (ES6)',
      'HTML5/SASS',
      'Axios',
      'JSON',
      'React.js',
      'JavaScript (ES6)',
      'HTML5/SASS',
      'Axios',
      'JSON',
    ],
    linkRepo: '#',
    linkDemo: '#',
    imgLink: 'https://via.placeholder.com/1920x1080',
  },
  {
    id: '04',
    name: 'Name4',
    description:
      'An individual effort creating a social travel app consuming TFLs public API and allows users to plan journeys as well as check for live travel updates. The app will include a social feature where users can post pictures and statuses mimicking a social media platform.',
    tech: [
      'React.js',
      'JavaScript (ES6)',
      'HTML5/SASS',
      'Axios',
      'JSON',
      'React.js',
      'JavaScript (ES6)',
      'HTML5/SASS',
      'Axios',
      'JSON',
    ],
    linkRepo: '#',
    linkDemo: '#',
    imgLink: 'https://via.placeholder.com/1920x1080',
  },
  {
    id: '05',
    name: 'Name5',
    description:
      'An individual effort creating a social travel app consuming TFLs public API and allows users to plan journeys as well as check for live travel updates. The app will include a social feature where users can post pictures and statuses mimicking a social media platform.',
    tech: [
      'React.js',
      'JavaScript (ES6)',
      'HTML5/SASS',
      'Axios',
      'JSON',
      'React.js',
      'JavaScript (ES6)',
      'HTML5/SASS',
      'Axios',
      'JSON',
    ],
    linkRepo: '#',
    linkDemo: '#',
    imgLink: 'https://via.placeholder.com/1920x1080',
  },
];
